Syukatsu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls")),
    path("search/", include("search.urls")),
    path("", include("core.urls")),
]

api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("sheet_list", views.get_sheet_list, name="get_sheet_list"),
    path("sheet_detail", views.get_sheet_detail, name="get_sheet_detail"),
    path("company_data", views.get_company_data, name="get_company_data"),
    path("add_sheet", views.add_sheet, name="add_sheet"),
    path("toggle_favorite", views.toggle_favorite, name="set_favorite"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.top_page, name="top_page"),
    path("main", views.main_page, name="main"),
    path("sheet/add", views.sheet_add, name="sheet_add"),
    path("sheet/<slug:company_id>", views.sheet_detail, name="sheet"),
    path("sheet/<slug:company_id>/edit", views.sheet_edit, name="sheet_edit"),
]

core/models.py
from django.db import models
from django.forms.models import model_to_dict

from account.models import CustomUser


class Company(models.Model):
    company_id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=120)
    main_domain = models.ForeignKey("MainDomain", on_delete=models.CASCADE, related_name="main_domain")
    sub_domain = models.ManyToManyField("SubDomain", related_name="sub_domain")
    year_founded = models.DateField(null=True)
    capital = models.CharField(max_length=100, null=True)
    revenue = models.CharField(max_length=100, null=True)
    employee = models.CharField(max_length=100, null=True)
    ave_age = models.CharField(max_length=100, null=True)
    grad_hire_last_year = models.CharField(max_length=100, null=True)
    prefectures = models.ManyToManyField("Prefecture", related_name="companies")
    offices = models.CharField(max_length=1000, null=True)
    working_time = models.CharField(max_length=300, null=True)
    salary = models.CharField(max_length=100, null=True)
    benefit = models.CharField(max_length=2000, null=True)
    motto = models.CharField(max_length=2000, null=True)
    business = models.CharField(max_length=2000, null=True)

    def __str__(self):
        return self.name

    def to_dict(self):
        d = model_to_dict(self, exclude=["main_domain", "sub_domain", "prefectures"])
        main_domain = {"main_domain": self.main_domain.name}
        sub_domain = {"sub_domain": [sd.name for sd in self.sub_domain.all()]}
        prefecture = {"prefecture": [pf.name for pf in self.prefectures.all()]}
        return {**d, **main_domain, **sub_domain, **prefecture}


class CompanySheet(models.Model):
    company_id = models.CharField(max_length=10)
    name = models.CharField(max_length=120)
    main_domain = models.ForeignKey("MainDomain", on_delete=models.CASCADE, related_name="cs_main_domain")
    sub_domain = models.ManyToManyField("SubDomain", related_name="cs_sub_domain")
    company_url = models.CharField(max_length=120, null=True)
    prefectures = models.ManyToManyField("Prefecture", related_name="cs_companies")
    year_founded = models.DateField(null=True)
    capital = models.BigIntegerField(null=True)
    revenue = models.BigIntegerField(null=True)
    employee = models.IntegerField(null=True)
    ave_age = models.FloatField(null=True)
    grad_hire_last_year = models.IntegerField(null=True)
    working_time_start = models.TimeField(null=True)
    working_time_end = models.TimeField(null=True)
    salary = models.IntegerField(null=True)
    benefit = models.CharField(max_length=1000, null=True)
    motto = models.CharField(max_length=1000, null=True)
    business = models.CharField(max_length=1000, null=True)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="created_sheet")
    # get reverse by companySheet.created_by.created_sheet.all()

    strength = models.CharField(max_length=1000, blank=True)
    weakness = models.CharField(max_length=1000, blank=True)

    interested = models.CharField(max_length=1000, blank=True)
    impression = models.CharField(max_length=1000, blank=True)

    note = models.CharField(max_length=2000, blank=True)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("company_id", "created_by"),)

    def to_dict(self):
        d = model_to_dict(self, exclude=["id", "main_domain", "sub_domain", "prefectures", "created_by"])
        main_domain = {"main_domain": self.main_domain.name}
        sub_domain = {"sub_domain": [sd.name for sd in self.sub_domain.all()]}
        prefecture = {"prefecture": [pf.name for pf in self.prefectures.all()]}
        return {**d, **main_domain, **sub_domain, **prefecture}


class MainDomain(models.Model):
    name = models.CharField(max_length=24, unique=True)

    def __str__(self):
        return self.name


class SubDomain(models.Model):
    name = models.CharField(max_length=24, unique=True)

    def __str__(self):
        return self.name


class Prefecture(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name

core/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required

from account.models import CustomUser
from .models import *
from .data_list import prefectures


def top_page(request):
    if request.user.is_authenticated:
        return redirect("core:main")
    return render(request, "core/top_page.html")


@login_required
def main_page(request):
    return render(request, "core/main_page.html")


@login_required
def sheet_detail(request, company_id):
    user = get_object_or_404(CustomUser, username=request.user.username)
    sheet = user.created_sheet.filter(company_id=company_id).first()
    sub_domain = sheet.sub_domain.all()
    return render(request, "core/sheet_detail.html", {"sheet": sheet, "sub_domain": sub_domain})


@login_required
def sheet_edit(request, company_id):
    user = get_object_or_404(CustomUser, username=request.user.username)
    sheet = user.created_sheet.filter(company_id=company_id).first()
    main_domain_all = MainDomain.objects.all()
    sub_domain_all = SubDomain.objects.all()
    main_domain_id = sheet.main_domain.id
    sub_domain_id = sheet.sub_domain.all().values_list("id", flat=True)
    prefectures_name = sheet.prefectures.all().values_list("name", flat=True)

    return render(request, "core/sheet_edit.html",
                  {"sheet": sheet,
                   "main_domain_all": main_domain_all,
                   "sub_domain_all": sub_domain_all,
                   "main_domain_id": main_domain_id,
                   "sub_domain_id": sub_domain_id,
                   "prefectures": prefectures,
                   "prefectures_name": prefectures_name,
                   }
                  )


@login_required
def sheet_add(request):
    main_domain = MainDomain.objects.all()
    sub_domain = SubDomain.objects.all()

    return render(request, "core/sheet_add.html",
                  {"main_domain": main_domain, "sub_domain": sub_domain, "prefectures": prefectures})

templates/core/main_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}Main Page{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static "js/sheet.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="row mt-4">
        <a class="ml-auto btn btn-outline-danger py-1" href="{% url 'core:sheet_add' %}">Add</a>
    </div>
    <div class="row mx-auto mt-2">
        <table id="company-list" class="table table-hover border">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col" class="w-25">企業</th>
                <th scope="col" class="w-25">Main Domain</th>
                <th scope="col" class="w-50">Sub Domain</th>
                <th scope="col" class="w-25"></th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <script>company_list('{% url "api:get_sheet_list" %}')</script>
{% endblock %}

templates/core/sheet_add.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Sheet{% endblock %}

{# Tempus Dominus BS4 docs: https://tempusdominus.github.io/bootstrap-4/Usage/ #}
{# Font Awesome: https://fontawesome.com/ #}
{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js"
            integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment-with-locales.min.js"
            integrity="sha512-kcvf1mExE8WCOLBL5re/9hLUHfaj8+LQrKlupTarmme+rwv8asLK4q6Ge32trTMBElPBP5sll4czZKNvps0VvA=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha512-2JBCbWoMJPH+Uj7Wq5OLub8E5edWHlTM4ar/YJkZh3plwB2INhhOC3eDoqHm1Za/ZOSksrLlURLoyXVdfQXqwg=="
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.css"
          integrity="sha512-PMjWzHVtwxdq7m7GIxBot5vdxUY+5aKP9wpKtvnNBZrVv1srI8tU6xvFMzG8crLNcMj/8Xl/WWmo/oAP/40p1g=="
          crossorigin="anonymous"/>
    <script src="{% static 'js/addSheet.js' %}"></script>
{% endblock %}
{% block content %}
    <div>
        <form action="{% url 'api:add_sheet' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="addInputCompanyID">Company ID</label>
                <div class="input-group">
                    <input id="addInputCompanyID" type="text" class="form-control" placeholder="Company ID"
                           name="company_id">
                    <div class="input-group-append" data-target="addInputCompanyID">
                        <button type="button" class="input-group-text btn" id="getCompanyData">
                            <i class="fas fa-cloud-download-alt"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="addInputCompanyName">Company Name</label>
                <input id="addInputCompanyName" type="text" class="form-control" placeholder="Company Name" name="name">
            </div>
            <div class="form-group">
                <label for="addInputCompanyURL">Company Website</label>
                <input id="addInputCompanyURL" type="text" class="form-control" placeholder="Company URL" name="url">
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputMainDomain">Main Domain</label>
                    <select id="addInputMainDomain" class="form-control" name="main_domain">
                        {% for md in main_domain %}
                            <option>{{ md.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col">
                    <label for="addInputSubDomain">Sub Domain</label>
                    <select id="addInputSubDomain" class="form-control" multiple name="sub_domain">
                        {% for sd in sub_domain %}
                            <option>{{ sd.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputFounded">Founded</label>
                    <div class="input-group date" id="addInputFoundedDatePicker" data-target-input="nearest">
                        <input id="addInputFounded" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputFoundedDatePicker" placeholder="Founded Year" name="year_founded">
                        <div class="input-group-append" data-target="#addInputFoundedDatePicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputEmployee">Employee</label>
                    <input id="addInputEmployee" type="number" class="form-control" placeholder="Employee"
                           name="employee">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputCapital">Capital</label>
                    <input id="addInputCapital" type="number" class="form-control" placeholder="Capital" name="capital">
                </div>
                <div class="form-group col">
                    <label for="addInputRevenue">Revenue</label>
                    <input id="addInputRevenue" type="number" class="form-control" placeholder="Revenue" name="revenue">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputWorkingTimeStart">Working Time Start</label>
                    <div class="input-group date" id="addInputWorkingTimeStartPicker" data-target-input="nearest">
                        <input id="addInputWorkingTimeStart" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputWorkingTimeStartPicker" placeholder="Working Time Start"
                               name="working_time_start">
                        <div class="input-group-append" data-target="#addInputWorkingTimeStartPicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fas fa-clock"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputWorkingTimeEnd">Working Time End</label>
                    <div class="input-group date" id="addInputWorkingTimeEndPicker" data-target-input="nearest">
                        <input id="addInputWorkingTimeEnd" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputWorkingTimeEndPicker" placeholder="Working Time End"
                               name="working_time_end">
                        <div class="input-group-append" data-target="#addInputWorkingTimeEndPicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fas fa-clock"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputPlace">Place</label>
                    <select id="addInputPlace" class="form-control" multiple name="offices">
                        {% for p in prefectures %}
                            {% if p.code == -1 %}
                                <option disabled>{{ p.name }}</option>
                            {% else %}
                                <option>{{ p.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputSalary">Salary</label>
                    <input id="addInputSalary" type="number" class="form-control" placeholder="Salary" name="salary">
                </div>
                <div class="form-group col">
                    <label for="addInputBenefits">Benefits</label>
                    <textarea class="form-control" id="addInputBenefits" rows="5" placeholder="Benefits"
                              name="benefit"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="addInputMotto">Motto</label>
                <textarea id="addInputMotto" type="number" class="form-control" rows="5" placeholder="Motto"
                          name="motto"></textarea>
            </div>
            <div class="form-group">
                <label for="addInputBusiness">Business</label>
                <textarea class="form-control" id="addInputBusiness" rows="5" placeholder="Business"
                          name="business"></textarea>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputStrength">Strength</label>
                    <textarea class="form-control" id="addInputStrength" rows="5" placeholder="Strength"
                              name="strength">{{ sheet.strength }}</textarea>
                </div>
                <div class="form-group col">
                    <label for="addInputWeakness">Weakness</label>
                    <textarea class="form-control" id="addInputWeakness" rows="5" placeholder="Weakness"
                              name="weakness">{{ sheet.weakness }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="addInputNote">Note</label>
                <textarea class="form-control" id="addInputNote" rows="5" placeholder="Note"
                          name="note">{{ sheet.note }}</textarea>
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
{% endblock %}
{% block bottom_script %}
    <script>
        $("#addInputFoundedDatePicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            viewMode: "years",
            format: "YYYY-MM",
            locale: "ja",
        });
        $("#addInputWorkingTimeStartPicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            format: "LT",
            locale: "ja",
        });
        $("#addInputWorkingTimeEndPicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            format: "LT",
            locale: "ja",
        });
        $("#addInputCompanyID").focusout(function (e) {
            checkCompanyId($(this), $(this).val());
        });
        $("#getCompanyData").click(function (e) {
            const obj = $("#addInputCompanyID")
            if (checkCompanyId(obj)) {
                getCompanyData(obj.val(), '{% url "api:get_company_data" %}')
            }
        })
    </script>
{% endblock %}

templates/core/sheet_edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Sheet{% endblock %}

{# Tempus Dominus BS4 docs: https://tempusdominus.github.io/bootstrap-4/Usage/ #}
{# Font Awesome: https://fontawesome.com/ #}
{% block head %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment.min.js"
            integrity="sha512-Q1f3TS3vSt1jQ8AwP2OuenztnLU6LwxgyyYOG1jgMW/cbEMHps/3wjvnl1P3WTrF3chJUWEoxDUEjMxDV8pujg=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.28.0/moment-with-locales.min.js"
            integrity="sha512-kcvf1mExE8WCOLBL5re/9hLUHfaj8+LQrKlupTarmme+rwv8asLK4q6Ge32trTMBElPBP5sll4czZKNvps0VvA=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha512-2JBCbWoMJPH+Uj7Wq5OLub8E5edWHlTM4ar/YJkZh3plwB2INhhOC3eDoqHm1Za/ZOSksrLlURLoyXVdfQXqwg=="
            crossorigin="anonymous"></script>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.css"
          integrity="sha512-PMjWzHVtwxdq7m7GIxBot5vdxUY+5aKP9wpKtvnNBZrVv1srI8tU6xvFMzG8crLNcMj/8Xl/WWmo/oAP/40p1g=="
          crossorigin="anonymous"/>
    <script src="{% static 'js/addSheet.js' %}"></script>
{% endblock %}
{% block content %}
    <div>
        <form action="{% url 'api:add_sheet' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="addInputCompanyID">Company ID</label>
                <div class="input-group">
                    <input id="addInputCompanyID" type="text" class="form-control" placeholder="Company ID"
                           name="company_id" readonly value="{{ sheet.company_id }}">
                    <div class="input-group-append" data-target="addInputCompanyID">
                        <button type="button" class="input-group-text btn" id="getCompanyData">
                            <i class="fas fa-cloud-download-alt"></i>
                        </button>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="addInputCompanyName">Company Name</label>
                <input id="addInputCompanyName" type="text" class="form-control" placeholder="Company Name" name="name"
                       value="{{ sheet.name }}">
            </div>
            <div class="form-group">
                <label for="addInputCompanyURL">Company Website</label>
                <input id="addInputCompanyURL" type="text" class="form-control" placeholder="Company URL" name="url">
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputMainDomain">Main Domain</label>
                    <select id="addInputMainDomain" class="form-control" name="main_domain">
                        {% for x in main_domain_all %}
                            {% if x.id == main_domain_id %}
                                <option selected>{{ x.name }}</option>
                            {% else %}
                                <option>{{ x.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col">
                    <label for="addInputSubDomain">Sub Domain</label>
                    <select id="addInputSubDomain" class="form-control" multiple name="sub_domain">
                        {% for x in sub_domain_all %}
                            {% if x.id in sub_domain_id %}
                                <option selected>{{ x.name }}</option>
                            {% else %}
                                <option>{{ x.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputFounded">Founded</label>
                    <div class="input-group date" id="addInputFoundedDatePicker" data-target-input="nearest">
                        <input id="addInputFounded" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputFoundedDatePicker" placeholder="Founded Year" name="year_founded"
                               value="{{ sheet.year_founded }}">
                        <div class="input-group-append" data-target="#addInputFoundedDatePicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fa fa-calendar"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputEmployee">Employee</label>
                    <input id="addInputEmployee" type="number" class="form-control" placeholder="Employee"
                           name="employee" value="{{ sheet.employee }}">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputCapital">Capital</label>
                    <input id="addInputCapital" type="number" class="form-control" placeholder="Capital" name="capital"
                           value="{{ sheet.capital }}">
                </div>
                <div class="form-group col">
                    <label for="addInputRevenue">Revenue</label>
                    <input id="addInputRevenue" type="number" class="form-control" placeholder="Revenue" name="revenue"
                           value="{{ sheet.revenue }}">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputWorkingTimeStart">Working Time Start</label>
                    <div class="input-group date" id="addInputWorkingTimeStartPicker" data-target-input="nearest">
                        <input id="addInputWorkingTimeStart" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputWorkingTimeStartPicker" placeholder="Working Time Start"
                               name="working_time_start" value="{{ sheet.working_time_start }}">
                        <div class="input-group-append" data-target="#addInputWorkingTimeStartPicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fas fa-clock"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputWorkingTimeEnd">Working Time End</label>
                    <div class="input-group date" id="addInputWorkingTimeEndPicker" data-target-input="nearest">
                        <input id="addInputWorkingTimeEnd" type="text" class="form-control datetimepicker-input"
                               data-target="#addInputWorkingTimeEndPicker" placeholder="Working Time End"
                               name="working_time_end" value="{{ sheet.working_time_end }}">
                        <div class="input-group-append" data-target="#addInputWorkingTimeEndPicker"
                             data-toggle="datetimepicker">
                            <div class="input-group-text">
                                <i class="fas fa-clock"></i>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group col">
                    <label for="addInputPlace">Place</label>
                    <select id="addInputPlace" class="form-control" multiple name="offices">
                        {% for p in prefectures %}
                            {% if p.code == -1 %}
                                <option disabled>{{ p.name }}</option>
                            {% else %}
                                {% if p.name in prefectures_name %}
                                    <option selected>{{ p.name }}</option>
                                {% else %}
                                    <option>{{ p.name }}</option>
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col">
                    <label for="addInputSalary">Salary</label>
                    <input id="addInputSalary" type="number" class="form-control" placeholder="Salary" name="salary"
                           value="{{ sheet.salary }}">
                </div>
                <div class="form-group col">
                    <label for="addInputBenefits">Benefits</label>
                    <textarea class="form-control" id="addInputBenefits" rows="3" placeholder="Benefits"
                              name="benefit">{{ sheet.benefit }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="addInputMotto">Motto</label>
                <textarea id="addInputMotto" type="number" class="form-control" rows="3" placeholder="Motto"
                          name="motto">{{ sheet.motto }}</textarea>
            </div>
            <div class="form-group">
                <label for="addInputBusiness">Business</label>
                <textarea class="form-control" id="addInputBusiness" rows="3" placeholder="Business"
                          name="business">{{ sheet.business }}</textarea>
            </div>
            <div class="form-group">
                <label for="addInputNote">Note</label>
                <textarea class="form-control" id="addInputNote" rows="3" placeholder="Note"
                          name="note">{{ sheet.note }}</textarea>
            </div>
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>
{% endblock %}
{% block bottom_script %}
    <script>
        $("#addInputFoundedDatePicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            viewMode: "years",
            format: "YYYY-MM",
            locale: "ja",
        });
        $("#addInputWorkingTimeStartPicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            format: "LT",
            locale: "ja",
        });
        $("#addInputWorkingTimeEndPicker").datetimepicker({
            timeZone: "Asia/Tokyo",
            format: "LT",
            locale: "ja",
        });
        $("#addInputCompanyID").focusout(function (e) {
            checkCompanyId($(this), $(this).val());
        });
        $("#getCompanyData").click(function (e) {
            const obj = $("#addInputCompanyID")
            if (checkCompanyId(obj)) {
                getCompanyData(obj.val(), '{% url "api:get_company_data" %}')
            }
        })
    </script>
{% endblock %}

templates/core/top_page.html
{% extends "base.html" %}
{% load static %}
{% block title %}Companalyze{% endblock %}
{% block content %}
<div class="container">
    <div class="top-image border rounded border-right">
        <img class="w-100" src="{% static 'images/Header.jpg' %}" alt="">
    </div>
    <div class="mt-3 text-center">
        <a class="btn btn-info text-white mx-2" href="account/signup">Register</a>
        <a class="btn btn-info text-white mx-2" href="account/login">Login</a>
    </div>
    <div class="text-center mt-5">
        <p>
            企業研究サポートサイト<br>
            企業の特徴や強み、自分に合っているかなどなど分析するときに使ってください
        </p>
        <p>
            リクナビの企業ID(URLの末尾r○○○○)を入力すると自動で企業情報が入力されます。
        </p>
    </div>
</div>
{% endblock %}