Syukatsu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("account/", include("account.urls")),
    path("account/", include("django.contrib.auth.urls")),
    path("api/", include("api.urls")),
    path("search/", include("search.urls")),
    path("", include("core.urls")),
]

account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("detail/", views.user_detail, name="user_detail")
]

api/urls.py
from django.urls import path
from . import views

app_name = "api"

urlpatterns = [
    path("sheet_list", views.get_sheet_list, name="get_sheet_list"),
    path("sheet_detail", views.get_sheet_detail, name="get_sheet_detail"),
    path("company_data", views.get_company_data, name="get_company_data"),
    path("add_sheet", views.add_sheet, name="add_sheet"),
    path("toggle_favorite", views.toggle_favorite, name="set_favorite"),
]

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.top_page, name="top_page"),
    path("main", views.main_page, name="main"),
    path("sheet/add", views.sheet_add, name="sheet_add"),
    path("sheet/<slug:company_id>", views.sheet_detail, name="sheet"),
    path("sheet/<slug:company_id>/edit", views.sheet_edit, name="sheet_edit"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
{# cdn libs: https://cdnjs.com/ #}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}Companalyze{% endblock %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"
            integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
            integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA=="
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
          integrity="sha512-aOG0c6nPNzGk+5zjwyJaoRUgCdOrfSDhmMID2u4+OIslr0GjpLKo7Xm0Ao3xmpM4T8AmIouRkqwj1nrdVsLKEQ=="
          crossorigin="anonymous"/>

    <link rel="stylesheet" href="{% static "style.css" %}">

    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"
            integrity="sha384-3Nqiqht3ZZEO8FKj7GR1upiI385J92VwWNLj+FqHxtLYxd9l+WYpeqSOrLh0T12c"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.6/lib/darkmode-js.min.js"></script>
    {% block head %}

    {% endblock %}
</head>
<body class="d-flex flex-column">
<div class="container" id="container">
    <header class="w-100 mx-auto">
        <nav class="navbar navbar-expand-lg navbar-light bg-light rounded-bottom py-1">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="{% url 'core:top_page' %}" class="nav-link">
                    <img src="{% static 'images/CompanalizeLogo.png' %}" alt="" style="height: 1rem;">
                </a></li>
            </ul>
            <ul class="navbar-nav">
                <div class="nav-item custom-control custom-switch d-flex align-items-center mr-4">
                    <input type="checkbox" class="custom-control-input" id="switch_darkmode"
                           onclick="darkmode.toggle()">
                    <label for="switch_darkmode" class="custom-control-label">Darkmode</label>
                </div>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'account:user_detail' %}"
                                            class="user nav-link">{{ user.username }}</a></li>
                    <li class="nav-item"><a href="{% url 'logout' %}" class="logout nav-link">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a href="{% url 'account:signup' %}" class="signup nav-link">Sign up</a></li>
                    <li class="nav-item"><a href="{% url 'login' %}" class="login nav-link">Login</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="content mx-auto my-4">
        {% block content %}{% endblock %}
    </div>
</div>
<footer class="footer w-100 text-center bg-light">
    <div class="container h-100 ">
        <small class="text-muted align-middle">Created by KK - 2020</small>
    </div>
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static "js/utils.js" %}"></script>

<script>
    const darkmode = new Darkmode();
    if (darkmode.isActivated()) {
        $("#switch_darkmode").prop("checked", true);
    } else {
        $("#switch_darkmode").prop("checked", false);
    }
</script>
{% block bottom_script %}
{% endblock %}
</body>
</html>